import { pool } from '../config/database.js'

/*
    Possible stretch feature:
        Student user account can view all reviews they have written
        Their "My Reviews" page can allow them to edit or delete their reviews
        Requires getReviewsByStudent
*/

const getReviewsByAdvisor = async (req, res) => {
    try {
        const advisorId = Number(req.params.advisorId);

        if (!Number.isInteger(advisorId) || advisorId <= 0) {
            return res.status(400).json({
                message: "Invalid advisor ID",
            });
        }

        // most recent reviews first displayed on top of page
        const results = await pool.query(
            `
                SELECT r.*,
                       u.username,
                       u.name,
                       u.avatar_url
                FROM reviews r
                LEFT JOIN users u ON r.user_id = u.id
                WHERE r.advisor_id = $1
                ORDER BY review_date DESC, review_id DESC
            `,
            [advisorId],
        );

        return res.status(200).json(results.rows);
    } catch (err) {
        console.error(err);

        return res.status(500).json({
            message: "Unable to retrieve advisor reviews",
        });
    }
}

const createReview = async (req, res) => {
    try {
        // ommit review_id, review_date because they are auto-generated by db
        const {
            advisor_id,
            overall_rating,
            communication_rating,
            availability_rating,
            comment,
            would_recommend,
        } = req.body;

        const userId = req.user?.id || null;
        const advisorId = Number(advisor_id);
        const overallRating = Number(overall_rating);
        const communicationRating = Number(communication_rating);
        const availabilityRating = Number(availability_rating);

        // make sure id's are valid
        if (!Number.isInteger(advisorId) || advisorId <= 0) {
            return res.status(400).json({
                message: "A valid advisor_id is required",
            });
        }

        const ratings = [
            overallRating,
            communicationRating,
            availabilityRating,
        ];

        // ratings must be integers between 1 and 5
        // user will have to type in number
        const ratingsAreValid = ratings.every(
            (rating) =>
                Number.isInteger(rating) &&
                rating >= 1 &&
                rating <= 5,
        );

        if (!ratingsAreValid) {
            return res.status(400).json({
                message: "All ratings must be whole numbers between 1 and 5",
            });
        }

        // user presses button to select yes or no, so must be boolean
        if (typeof would_recommend !== "boolean") {
            return res.status(400).json({
                message: "would_recommend must be true or false",
            });
        }

        // make sure description comment is all strings
        if (
            comment !== undefined &&
            comment !== null &&
            typeof comment !== "string"
        ) {
            return res.status(400).json({
                message: "comment must be a string",
            });
        }

        // Prevent duplicate reviews from logged-in users for the same advisor
        if (userId) {
            const existingReview = await pool.query(
                `SELECT review_id FROM reviews WHERE advisor_id = $1 AND user_id = $2`,
                [advisorId, userId]
            );
            if (existingReview.rows.length > 0) {
                return res.status(400).json({
                    message: "You have already submitted a review for this advisor.",
                });
            }
        }

        const results = await pool.query(
            `
                INSERT INTO reviews (
                    advisor_id,
                    user_id,
                    overall_rating,
                    communication_rating,
                    availability_rating,
                    comment,
                    would_recommend
                )
                VALUES ($1, $2, $3, $4, $5, $6, $7)
                RETURNING *
            `,
            [
                advisorId,
                userId,
                overallRating,
                communicationRating,
                availabilityRating,
                comment?.trim() || null,
                would_recommend
            ],
        );

        return res.status(201).json(results.rows[0]);
    } catch (err) {
        // Duplicate review constraint violation
        if (err.code === "23505") {
            return res.status(400).json({
                message: "You have already submitted a review for this advisor.",
            });
        }

        // advisor_id doesn't reference existing row
        if (err.code === "23503") {
            return res.status(400).json({
                message: "Advisor does not exist",
            });
        }

        // db CHECK constraint failed (e.g. rating range)
        if (err.code === "23514") {
            return res.status(400).json({
                message: "Ratings must be between 1 and 5",
            });
        }

        console.error(err);

        return res.status(500).json({
            message: "Unable to create review",
        });
    }
};

const updateReview = async (req, res) => {
    try {
        const reviewId = Number(req.params.reviewId);

        if (!Number.isInteger(reviewId) || reviewId <= 0) {
            return res.status(400).json({
                message: "Invalid review ID",
            });
        }

        // ommit review_id, review_date because they are auto-generated by db
        const {
            advisor_id,
            overall_rating,
            communication_rating,
            availability_rating,
            comment,
            would_recommend
        } = req.body;

        // reject empty request body
        const noFieldsProvided =
            advisor_id === undefined &&
            overall_rating === undefined &&
            communication_rating === undefined &&
            availability_rating === undefined &&
            comment === undefined &&
            would_recommend === undefined

        if (noFieldsProvided) {
            return res.status(400).json({
                message: "At least one field must be provided"
            })
        }

        const advisorId =
            advisor_id === undefined
                ? null
                : Number(advisor_id);

        const overallRating =
            overall_rating === undefined
                ? null
                : Number(overall_rating);

        const communicationRating =
            communication_rating === undefined
                ? null
                : Number(communication_rating);

        const availabilityRating =
            availability_rating === undefined
                ? null
                : Number(availability_rating);

        if (
            advisor_id !== undefined &&
            (!Number.isInteger(advisorId) || advisorId <= 0)
        ) {
            return res.status(400).json({
                message: "Invalid advisor ID",
            });
        }

        const ratings = [
            {
                provided: overall_rating !== undefined,
                value: overallRating,
            },
            {
                provided: communication_rating !== undefined,
                value: communicationRating,
            },
            {
                provided: availability_rating !== undefined,
                value: availabilityRating,
            },
        ];

        // .some() checks whether at least one item in array passes condition
        const invalidRating = ratings.some(
            ({ provided, value }) =>
                provided &&
                (!Number.isInteger(value) || value < 1 || value > 5),
        );

        if (invalidRating) {
            return res.status(400).json({
                message: "Ratings must be whole numbers between 1 and 5",
            });
        }

        if (
            would_recommend !== undefined &&
            typeof would_recommend !== "boolean"
        ) {
            return res.status(400).json({
                message: "would_recommend must be true or false",
            });
        }

        if (
            comment !== undefined &&
            comment !== null &&
            typeof comment !== "string"
        ) {
            return res.status(400).json({
                message: "comment must be a string",
            });
        }

        // Fetch the review first to check ownership
        const reviewResult = await pool.query(
            `SELECT user_id FROM reviews WHERE review_id = $1`,
            [reviewId]
        );

        if (reviewResult.rows.length === 0) {
            return res.status(404).json({
                message: "Review not found",
            });
        }

        const review = reviewResult.rows[0];

        // Anonymous reviews (user_id IS NULL) cannot be edited by anyone
        // Logged-in reviews can only be edited by their author
        if (review.user_id === null || review.user_id !== req.user.id) {
            return res.status(403).json({
                message: "Forbidden. You can only edit your own reviews.",
            });
        }

        const results = await pool.query(
            `
                WITH updated AS (
                    UPDATE reviews
                    SET advisor_id = COALESCE($1, advisor_id),
                        overall_rating = COALESCE($2, overall_rating),
                        communication_rating = COALESCE($3, communication_rating),
                        availability_rating = COALESCE($4, availability_rating),
                        comment = CASE WHEN $5::text IS NULL THEN comment ELSE NULLIF($5::text, '') END,
                        would_recommend = COALESCE($6, would_recommend)
                    WHERE review_id = $7
                    RETURNING *
                )
                SELECT r.*, u.username, u.name, u.avatar_url
                FROM updated r
                LEFT JOIN users u ON r.user_id = u.id
            `,
            [
                advisorId,
                overallRating,
                communicationRating,
                availabilityRating,
                comment === undefined
                    ? null
                    : (comment === null ? "" : comment.trim()),
                would_recommend === undefined
                    ? null
                    : would_recommend,
                reviewId
            ],
        );

        if (results.rows.length === 0) {
            return res.status(404).json({
                message: "Review not found",
            });
        }

        return res.status(200).json(results.rows[0]);
    } catch (err) {
        // advisor_id doesn't exist
        if (err.code === "23503") {
            return res.status(400).json({
                message: "Advisor does not exist",
            });
        }

        // CHECK constraint failed (e.g. rating range)
        if (err.code === "23514") {
            return res.status(400).json({
                message: "Ratings must be between 1 and 5",
            });
        }

        console.error(err);

        return res.status(500).json({
            message: "Unable to update review",
        });
    }
};

const deleteReview = async (req, res) => {
    try {
        const reviewId = Number(req.params.reviewId);

        if (!Number.isInteger(reviewId) || reviewId <= 0) {
            return res.status(400).json({
                message: "Invalid review ID",
            });
        }

        // Fetch the review first to check ownership
        const reviewResult = await pool.query(
            `SELECT user_id FROM reviews WHERE review_id = $1`,
            [reviewId]
        );

        if (reviewResult.rows.length === 0) {
            return res.status(404).json({
                message: "Review not found",
            });
        }

        const review = reviewResult.rows[0];

        // Anonymous reviews (user_id IS NULL) cannot be deleted by anyone
        // Logged-in reviews can only be deleted by their author
        if (review.user_id === null || review.user_id !== req.user.id) {
            return res.status(403).json({
                message: "Forbidden. You can only delete your own reviews.",
            });
        }

        const results = await pool.query(
            `
                DELETE FROM reviews
                WHERE review_id = $1
                RETURNING *
            `,
            [reviewId],
        );

        return res.status(200).json({
            message: "Review deleted successfully",
            deletedReview: results.rows[0],
        });
    } catch (err) {
        console.error(err);

        return res.status(500).json({
            message: "Unable to delete review",
        });
    }
};

export default {
  getReviewsByAdvisor,
  createReview,
  updateReview,
  deleteReview
}
